version: "3.6"
services:
  hasura:
    image: hasura/graphql-engine:v1.0.0-beta.6
    env_file: ../../.env
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    volumes:
      - ./migrations:/hasura-migrations
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
